export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>ArmyClub</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<style>@import"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css";
</style><link rel="stylesheet" href="styles-5NTETIBU.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-5NTETIBU.css"></noscript><link rel="preload" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" as="style"><style ng-app-id="ng">html[_ngcontent-ng-c1374557969], body[_ngcontent-ng-c1374557969]{height:100%;margin:0;display:flex;flex-direction:column}.main-content[_ngcontent-ng-c1374557969]{flex:1}.footer[_ngcontent-ng-c1374557969]{background-color:#343a40;color:#fff;text-align:center;padding:20px 0;margin-top:auto}.container[_ngcontent-ng-c1374557969]{max-width:1200px;margin:0 auto;padding:0 15px}</style></head>
<body><!--nghm-->
  <app-root ng-version="19.0.4" ngh="1" ng-server-context="ssg"><app-menu ngh="0"><header class="bg-primary text-white py-3 d-flex justify-content-between align-items-center"><img src="assets/Army.jpg" alt="Army Logo" class="ms-4" style="height: 70px;"><div class="text-center flex-grow-1"><h1 class="mb-0">Army Club</h1><nav class="nav justify-content-center"><a href="/home" class="nav-link text-white">Home</a><a href="#media" class="nav-link text-white">Media</a><a href="#winners" class="nav-link text-white">Winners</a><a href="/contact" class="nav-link text-white">Contact Us</a></nav></div><div class="me-3"></div></header></app-menu><router-outlet></router-outlet><app-contact-us ngh="0"><section id="contact" class="my-5"><h2 class="text-center mb-4">Contact Us</h2><form novalidate class="needs-validation mx-auto p-4 border rounded" style="max-width: 600px;"><div class="mb-3"><label for="name" class="form-label">Name:</label><input type="text" id="name" name="name" required class="form-control"><div class="invalid-feedback"> Please enter your name. </div></div><div class="mb-3"><label for="email" class="form-label">Email:</label><input type="email" id="email" name="email" required class="form-control"><div class="invalid-feedback"> Please enter a valid email address. </div></div><div class="mb-3"><label for="message" class="form-label">Message:</label><textarea id="message" name="message" rows="5" required class="form-control"></textarea><div class="invalid-feedback"> Please enter your message. </div></div><button type="submit" class="btn btn-primary w-100">Submit</button></form></section></app-contact-us><!----><app-footer _nghost-ng-c1374557969 ngh="0"><footer _ngcontent-ng-c1374557969 class="bg-primary text-white text-center py-3"><p _ngcontent-ng-c1374557969>© 2024 Army Club. All rights reserved.</p></footer></app-footer></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-OQEBSAN5.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"c":{"1":[{"i":"c3562140832","r":1}]}}]}</script></body></html>`;